version: '3'

services:
  account-rdbms:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - './.postgresql/:/var/lib/postgresql/account'
    ports:
      - '5432:5432'
    command: -p 5432

  emergency-rdbms:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - './.postgresql/:/var/lib/postgresql/emergency'
    ports:
      - "5433:5433"
    command: -p 5433

  hotline-rdbms:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - './.postgresql/:/var/lib/postgresql/hotline'
    ports:
      - "5434:5434"
    command: -p 5434


  messenger-rdbms:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - './.postgresql/:/var/lib/postgresql/messenger'
    ports:
      - "5435:5435"
    command: -p 5435


  accounts-service:
    build: ./accounts
    environment:
      - GORM_NAME=postgresdb
      - GORM_USER=postgres
      - GORM_PASS=pgpassword
      - GORM_HOST=account-rdbms
      - GORM_PORT=5432
    volumes:
      - './:/app'
    ports:
      - "80:80"
    links:
      - account-rdbms

  emergency-service:
    build: ./emergency
    environment:
      - GORM_NAME=postgresdb
      - GORM_USER=postgres
      - GORM_PASS=pgpassword
      - GORM_HOST=emergency-rdbms
      - GORM_PORT=5433
    volumes:
      - './:/app'
    ports:
      - "81:81"
    links:
      - emergency-rdbms

  hotline-service:
    build: ./hotline
    environment:
      - GORM_NAME=postgresdb
      - GORM_USER=postgres
      - GORM_PASS=pgpassword
      - GORM_HOST=hotline-rdbms
      - GORM_PORT=5434
    volumes:
      - './:/app'
    ports:
      - "82:82"
    links:
      - hotline-rdbms

  messenger-service:
    build: ./messenger
    environment:
      - GORM_NAME=postgresdb
      - GORM_USER=postgres
      - GORM_PASS=pgpassword
      - GORM_HOST=messenger-rdbms
      - GORM_PORT=5435
    volumes:
      - './:/app'
    ports:
      - "83:83"
    links:
      - messenger-rdbms