version: '3'

services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    #   environment:
    #      JENKINS_JAVA_OPTIONS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
    privileged: true
    user: root
    ports:
      - 8888:8080
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /home/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /etc/timezone:/etc/timezone
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '5'