service:
  name: "SosApp"
  port: 82
  endpoint: "/SosApp/hotline"

token:
  secret: "SosAppToken"

role:
  user: "/user"
  admin: "/admin"

jwt:
  secret: "SosApp"

url:
  account: "http://34.143.165.150:80/SosApp/accounts/"
  emergency: "http://34.143.165.150:81/SosApp/emergency/"
  hotline: "http://34.143.165.150:82/SosApp/hotline/"
  messenger: "http://34.143.165.150:83/SosApp/messenger/"
