service:
  name: "SosApp"
  port: 81
  endpoint: "/SosApp/emergency"

role:
  user: "/user"
  admin: "/admin"

jwt:
  secret: "SosApp"

url:
  account: "http://127.0.0.1:80/SosApp/accounts/"
  emergency: "http://127.0.0.1:81/SosApp/emergency/"
  hotline: "http://127.0.0.1:82/SosApp/hotline/"
  messenger: "http://127.0.0.1:83/SosApp/messenger/"