service:
  name: "SosApp"
  port: 83
  endpoint: "/SosApp/messenger"

token:
  secret: "SosAppToken"

role:
  user: "/user"
  admin: "/admin"
  ops: "/ops"

jwt:
  secret: "SosApp"

url:
  account: "http://35.229.220.89:80/SosApp/accounts/"
  emergency: "http://35.229.220.89:81/SosApp/emergency/"
  hotline: "http://35.229.220.89:82/SosApp/hotline/"
  messenger: "http://35.229.220.89:83/SosApp/messenger/"