service:
  name: "SosApp"
  port: 80
  endpoint: "/SosApp/accounts"

role:
  user: "/user"
  admin: "/admin"
  ops: "/ops"

jwt:
  secret: "SosApp"

url:
  account: "http://localhost:80/SosApp/accounts/"
  emergency: "http://localhost:81/SosApp/emergency/"
  hotline: "http://localhost:82/SosApp/hotline/"
  messenger: "http://localhost.89:83/SosApp/messenger/"
