service:
  name: "SosApp"
  port: 80
  endpoint: "/SosApp/accounts"

role:
  user: "/user"
  admin: "/admin"

jwt:
  secret: "SosApp"

url:
  account: "localhost:80/SosApp/accounts/"
  emergency: "localhost:81/SosApp/emergency/"
  hotline: "localhost:82/SosApp/hotline/"
  messenger: "localhost:83/SosApp/messenger/"
